# -*- coding: utf-8 -*-
"""English for the per-food note and tip lines in templates/analyzer.html.

Those 522 foods each carry a one-line nutrition note and a one-line practical
tip, authored in Arabic. Unlike the meal strings these are prose, not
compositions of food terms, so a glossary cannot render them -- each is
translated individually here.

Keys are the exact Arabic strings from the FOODS array. tools/apply_food_en.py
reads this map and writes note_en / tip_en into the template, so the template
stays the single source of truth for what the page ships.

Anything missing from this map keeps its Arabic, which is visible rather than
silently wrong.
"""

NOTES_EN = {
    # ── poultry ──
    "مصدر ممتاز للبروتين الكامل بدون دهون.": "Excellent source of complete protein with no fat.",
    "بروتين عالي مع دهون متوسطة.": "High protein with moderate fat.",
    "بروتين جيد لكن الجلد يرفع الدهون.": "Good protein, but the skin raises the fat.",
    "بديل أخف من اللحم المفروم.": "A lighter alternative to minced beef.",
    "غنية بالحديد وفيتامين A.": "Rich in iron and vitamin A.",
    "بروتين عالي وسعرات قليلة جداً.": "High protein and very few calories.",
    "بروتين عالي وقليل الدهون.": "High protein and low fat.",
    "بروتين عالي مع دهون.": "High protein, with fat.",
    "بروتين جيد وطعم مميز.": "Good protein and a distinctive flavour.",
    "شعبي وغني بالحديد.": "Popular and rich in iron.",
    # ── meat ──
    "غني بالحديد والزنك وB12.": "Rich in iron, zinc and B12.",
    "اختار قليل الدهن.": "Choose the lean cut.",
    "دهون أعلى — طعم أغنى.": "Higher in fat, richer in flavour.",
    "أطرى قطعية وأقلها دهون.": "The tenderest cut and the leanest.",
    "دهون أعلى من البقري.": "Higher in fat than beef.",
    "أقل دهون من الضأن.": "Leaner than lamb.",
    "كنز من الحديد وفيتامين A.": "A treasure trove of iron and vitamin A.",
    "طري وغني بـ B12.": "Tender and rich in B12.",
    "كولاجين عالي جداً.": "Very high in collagen.",
    "محشي رز — سعراته من الحشو.": "Stuffed with rice, so the calories come from the filling.",
    "مصنّع — دهون وملح عاليين.": "Processed, high in fat and salt.",
    "مصنّع بدهون عالية.": "Processed and high in fat.",
    "مصنّع حار — دهون عالية.": "Processed and spicy, high in fat.",
    "بروتين عالي جداً بس مملحة.": "Very high protein, but heavily salted.",
    "أخف من البقري الكبير.": "Lighter than mature beef.",
    "كولاجين عالي — للحلة والفرن.": "High in collagen, for stewing and roasting.",
    "مشهورة مشوية.": "Best known grilled.",
    "أعضاء غنية بالحديد وB12.": "Organ meat, rich in iron and B12.",
    "حديد وزنك.": "Iron and zinc.",
    "كوليسترول عالي جداً.": "Very high in cholesterol.",
    "مصنع ومملح.": "Processed and salted.",
    "بروتين مركز للرحلات.": "Concentrated protein for trips.",
    # ── fish ──
    "بروتين عالي وقليل الدهن.": "High protein and low fat.",
    "أوميجا 3 عالية جداً.": "Very high in omega 3.",
    "بروتين سريع وعملي.": "Quick, practical protein.",
    "نفس البروتين بدهون أعلى.": "The same protein with more fat.",
    "غني بأوميجا 3 والكالسيوم.": "Rich in omega 3 and calcium.",
    "أوميجا 3 عالية.": "High in omega 3.",
    "أبيض خفيف وفاخر.": "Light white fish, and a premium one.",
    "بروتين عالي.": "High in protein.",
    "شعبي ولذيذ مشوي.": "Popular and delicious grilled.",
    "بروتين عالي وسعرات قليلة.": "High protein and few calories.",
    "بروتين خفيف وزنك عالي.": "Light protein and high in zinc.",
    "قليل السعرات جداً.": "Very low in calories.",
    "بروتين نقي فاخر.": "Pure, premium protein.",
    "رخيص وسهل التحضير.": "Cheap and easy to prepare.",
    "أوميجا 3 لكن مملحة جداً.": "Omega 3, but very heavily salted.",
    "مملح ومخمر.": "Salted and fermented.",
    "الفيليه أخف من السمكة الكاملة.": "The fillet is lighter than the whole fish.",
    "أوميجا 3 بس مملح.": "Omega 3, but salted.",
    "بروتين هائل لكن ملح أعلى.": "Enormous protein, but higher in salt.",
    "حديد وB12 ممتازين.": "Excellent iron and B12.",
    "أخف الأسماك البيضاء.": "The lightest of the white fish.",
    "بروتين عالي جداً.": "Very high in protein.",
    "كالسيوم بالعظم الطري.": "Calcium, from the soft bones.",
    "أوميجا 3 اقتصادية.": "Affordable omega 3.",
    "متبلة جاهزة.": "Ready seasoned.",
    "بروتين عالي جاهز.": "High protein, ready to eat.",
    "مصنعة.": "Processed.",
    "أخف من اللحم المجمد.": "Lighter than frozen beef.",
    "القلي ضاعف الدهون.": "Frying has doubled the fat.",
    "أخف اللانشون.": "The lightest of the cold cuts.",
    "أخف من البقري.": "Lighter than beef.",
    "بروتين متكامل.": "A complete protein.",
    "بروتين خالص بدون دهون.": "Pure protein with no fat.",
    "فيتامينات ودهون مركزة.": "Concentrated vitamins and fat.",
    "كالسيوم وفيتامين D.": "Calcium and vitamin D.",
    "نفس الكالسيوم بدون دهون.": "The same calcium without the fat.",
    "بروبيوتيك مفيد للهضم.": "Probiotics that help digestion.",
    "بروتين وبروبيوتيك.": "Protein and probiotics.",
    "بروتين أعلى من العادي.": "Higher in protein than the regular kind.",
    "خفيف ومنعش.": "Light and refreshing.",
    "قليل الدهن وعالي البروتين.": "Low in fat and high in protein.",
    "كالسيوم عالي.": "High in calcium.",
    "نصف دهون العادية.": "Half the fat of the regular kind.",
    "طاقة مركزة.": "Concentrated energy.",
    "دهون عالية.": "High in fat.",
    "للشوي — ملح عالي.": "Made for grilling, and high in salt.",
    "كريمية وأخف من الجبن.": "Creamy, and lighter than cheese.",
    "دهون شبه خالصة.": "Almost pure fat.",
    "دهون مشبعة مركزة.": "Concentrated saturated fat.",
    "أعلى طعام في السعرات.": "The most calorie-dense food there is.",
    "بروتين نباتي وألياف.": "Plant protein and fibre.",
    "إضافات بترفع السعرات.": "The additions push the calories up.",
    "حديد وبروتين — شوربة الشتاء.": "Iron and protein — the winter soup.",
    "ألياف أعلى من الأصفر.": "More fibre than the yellow kind.",
    "بروتين وألياف ممتازة.": "Excellent protein and fibre.",
    "الطحينة بتزود الدهون الصحية.": "The tahini adds healthy fats.",
    "بروتين نباتي عالي.": "High in plant protein.",
    "خفيفة على المعدة.": "Easy on the stomach.",
    "حلاوة طبيعية وألياف.": "Natural sweetness and fibre.",
    "أعلى بقوليات في البروتين!": "The highest-protein legume there is.",
    "مقلية — بتشرب زيت.": "Deep-fried, so it soaks up oil.",
    "تقنياً بقوليات مش مكسرات!": "Technically a legume, not a nut.",
    "بروتين ودهون صحية.": "Protein and healthy fats.",
    "بروتين كامل نباتي.": "A complete plant protein.",
    "بديل اللحم للنباتيين.": "The vegetarian stand-in for meat.",
    "معتقة مصرية — ملح ودهون.": "An aged Egyptian cheese: salt and fat.",
    "بيضاء مملحة.": "White and salted.",
    "قديمة حادة الطعم.": "Aged, with a sharp flavour.",
    "مخمرة صعيدية قليلة الدهن نسبياً.": "A fermented Upper Egyptian cheese, relatively low in fat.",
    "للبيتزا الدايت.": "For diet pizza.",
    "نباتي دسم.": "Plant-based but rich.",
    "أخف بدائل الحليب.": "The lightest of the milk alternatives.",
    "كريمي طبيعي.": "Naturally creamy.",
    "مركز — يتحسب بالمعلقة.": "Concentrated — count it by the spoon.",
    "زبادي مخفوق بالملح.": "Yogurt whisked with salt.",
    "الإنبات بيزود الفيتامينات.": "Sprouting boosts the vitamins.",
    "فول مهروس بالخضرة.": "Mashed fava beans with greens.",
    "بروتين مزدوج.": "A double dose of protein.",
    "للتشيلي والسلطات.": "For chilli and salads.",
    "ألياف من الأعلى.": "Among the highest in fibre.",
    "إضافة الجبن بتضيف 60 سعرة.": "Adding the cheese adds 60 calories.",
    "السمنة ضاعفت السعرات.": "The ghee has doubled the calories.",
    "سكر مضاف غالباً.": "Usually has added sugar.",
    "نص دسم العادية.": "Half the fat of the regular kind.",
    "عملي وسريع.": "Practical and quick.",
    "جاهز للسلطات.": "Ready for salads.",
    "الصلصة فيها سكر أحياناً.": "The sauce sometimes contains sugar.",
    "طاقة سريعة.": "Fast energy.",
    "ألياف أعلى وهضم أبطأ.": "More fibre and slower to digest.",
    "مؤشر جلايسيمي أقل من العادي.": "A lower glycaemic index than the regular kind.",
    "طاقة جيدة قبل التمرين.": "Good energy before training.",
    "ألياف مضاعفة.": "Double the fibre.",
    "الرغيف ≈ 90-110 جم.": "One loaf is roughly 90-110 g.",
    "دقيق أبيض.": "White flour.",
    "ألياف عالية.": "High in fibre.",
    "الشريحة ≈ 25 جم.": "One slice is roughly 25 g.",
    "ألياف وبروتين أعلى.": "More fibre and more protein.",
    "ملك حبوب الفطار.": "The king of breakfast grains.",
    "سكريات سريعة.": "Fast-releasing sugars.",
    "أخف نشويات — ألياف ممتازة.": "The lightest starch, with excellent fibre.",
    "خفيف وسريع التحضير.": "Light and quick to prepare.",
    "قمح أخضر مدخن — بروتين أعلى.": "Smoked green wheat, higher in protein.",
    "بروتين كامل نادر في النشويات.": "A complete protein, which is rare among starches.",
    "مشبعة جداً بالنسبة لسعراتها.": "Very filling for the calories.",
    "سعرات مضاعفة 3 مرات.": "Three times the calories.",
    "فيتامين A ممتاز.": "Excellent vitamin A.",
    "ألياف وطاقة.": "Fibre and energy.",
    "أساس المخبوزات.": "The basis of all baking.",
    "في الأرز أو باللبن.": "Used in rice or cooked with milk.",
    "مقلية مسبقاً + ملح عالي.": "Pre-fried and high in salt.",
    "السمنة بتضيف 35 سعرة للحصة.": "The ghee adds 35 calories per portion.",
    "الصلصة الحمرا أخف الصوصات.": "Red sauce is the lightest of the sauces.",
    "الرغيف ≈ 60 جم.": "One loaf is roughly 60 g.",
    "القطعة ≈ 60-70 جم.": "One piece is roughly 60-70 g.",
    "رقيق شامي.": "A thin Levantine flatbread.",
    "بيتا جلوكان مفيد للكوليسترول.": "Beta-glucan, which helps with cholesterol.",
    "ناشف يستخدم في الحلو والحادق.": "Dry sheets, used in both sweet and savoury dishes.",
    "العجينة الرقيقة توفر ثلث السعرات.": "A thin base saves a third of the calories.",
    "مطحون أنعم — امتصاص أسرع.": "Ground finer, so absorbed faster.",
    "شوفان محمص بعسل وزيت.": "Oats toasted with honey and oil.",
    "عطري آسيوي.": "An aromatic Asian rice.",
    "خالي جلوتين.": "Gluten-free.",
    "3 أكواب مفرقعة = 90 سعرة بس!": "3 cups popped is only 90 calories.",
    "الزبدة قلبته.": "The butter changes everything.",
    "قمح باللبن — فطار مشبع.": "Wheat with milk, a filling breakfast.",
    "ناشف ومقرمش.": "Dry and crunchy.",
    "مدعم بالحديد للرضع.": "Iron-fortified for infants.",
    "طرية للأطفال والكبار.": "Soft, for children and adults alike.",
    "مياه وانتعاش.": "Water and freshness.",
    "ليكوبين مضاد أكسدة.": "Lycopene, an antioxidant.",
    "حجم كبير سعرات صفرية.": "Plenty of volume for virtually no calories.",
    "حديد وفوليك.": "Iron and folate.",
    "حديد وفيتامين K.": "Iron and vitamin K.",
    "ألياف وحديد.": "Fibre and iron.",
    "خفيفة ومتعددة الاستخدام.": "Light and versatile.",
    "إسفنجي — بيشرب الزيت.": "Spongy, so it soaks up oil.",
    "فيتامين C أعلى من البرتقال.": "More vitamin C than an orange.",
    "بيتا كاروتين للنظر.": "Beta-carotene, good for eyesight.",
    "ملك الخضار — مضادات سرطان.": "The king of vegetables, with anti-cancer compounds.",
    "بديل الأرز في الكيتو.": "The keto stand-in for rice.",
    "رخيص ومفيد.": "Cheap and good for you.",
    "ألياف لزجة مفيدة للسكر.": "Its mucilaginous fibre helps with blood sugar.",
    "خفيفة وسريعة.": "Light and quick.",
    "مضاد التهابات طبيعي.": "A natural anti-inflammatory.",
    "مضاد حيوي طبيعي.": "A natural antibiotic.",
    "بيحسن تدفق الدم والأداء الرياضي.": "Improves blood flow and athletic performance.",
    "منظف طبيعي.": "A natural cleanser.",
    "طعم اللحم بسعرات الخضار.": "The savouriness of meat at the calorie cost of a vegetable.",
    "حسب الحشو.": "Depends on the filling.",
    "الأرز والزيت هما السعرات.": "The rice and oil are where the calories are.",
    "من غير صوص!": "Without dressing!",
    "دهون صحية بس مركزة.": "Healthy fats, but concentrated.",
    "باذنجان مشوي بالطحينة.": "Grilled eggplant with tahini.",
    "مفيد جداً للكبد والهضم.": "Very good for the liver and digestion.",
    "سعرات شبه صفرية.": "Almost no calories.",
    "عيلة البصل — مفيد للقلب.": "In the onion family, good for the heart.",
    "نشوي أكتر منه خضار.": "More of a starch than a vegetable.",
    "حلاوة طبيعية وفيتامين A.": "Natural sweetness and vitamin A.",
    "خفيف جداً.": "Very light.",
    "صفر سعرات لكن ملح عالي.": "No calories, but high in salt.",
    "فاتح شهية مملح.": "A salty appetiser.",
    "دهون صحية بس مملح.": "Healthy fats, but salted.",
    "أخف ملحاً من الأخضر غالباً.": "Usually less salty than green olives.",
    "أعلى كثافة غذائية بأقل سعرات.": "The highest nutrient density for the fewest calories.",
    "كرنب مصغر مركز الفوائد.": "Miniature cabbages with concentrated benefits.",
    "مدر وفوليك عالي.": "A diuretic, and high in folate.",
    "الكوز المتوسط ≈ 90 جم.": "A medium cob is roughly 90 g.",
    "كابسيسين يرفع الحرق.": "Capsaicin, which raises calorie burn.",
    "سناك سلطة حلو.": "A sweet salad snack.",
    "كراميل طبيعي بدون إضافات.": "Natural caramel with nothing added.",
    "حلوة وجاهزة.": "Sweet and ready to eat.",
    "محشي فلفل أو جزر.": "Stuffed with pepper or carrot.",
    "عملي للبيتزا والصوصات.": "Handy for pizza and sauces.",
    "حلاوة مركزة بالشوي.": "Roasting concentrates the sweetness.",
    "مركزة النكهة والسعرات.": "Concentrated in both flavour and calories.",
    "مخلل شهير — طازج أصح.": "Famous pickled, but healthier fresh.",
    "أنثوسيانين مضاد أكسدة.": "Anthocyanins, an antioxidant.",
    "مقرمش ومنعش.": "Crunchy and refreshing.",
    "أغنى من الآيسبرج.": "More nutritious than iceberg.",
    "نفس فوائد الطازج تقريباً.": "Almost the same benefits as fresh.",
    "جاهز للطبخ.": "Ready to cook.",
    "كلاسيكية سريعة.": "A quick classic.",
    "للسموذي طول السنة.": "For smoothies all year round.",
    "قطع جاهزة.": "Ready-cut pieces.",
    "سر السموذي الكريمي.": "The secret to a creamy smoothie.",
    "ألياف وبكتين للشبع.": "Fibre and pectin, which keep you full.",
    "بوتاسيوم وطاقة سريعة.": "Potassium and fast energy.",
    "فيتامين C.": "Vitamin C.",
    "سهل التقشير — سناك الشتاء.": "Easy to peel, the winter snack.",
    "سكر طبيعي عالي.": "High in natural sugar.",
    "92% مياه.": "92% water.",
    "منعش وفيتامين A.": "Refreshing, with vitamin A.",
    "ملكة الفاكهة — سكرها متوسط.": "The queen of fruit, with a moderate sugar content.",
    "أقل الفواكه سكراً.": "The lowest-sugar fruit there is.",
    "سكر مركز جداً.": "Very concentrated sugar.",
    "ألياف ممتازة.": "Excellent fibre.",
    "مضادات أكسدة قوية.": "Powerful antioxidants.",
    "فيتامين C أعلى فاكهة!": "The highest vitamin C of any fruit.",
    "ألياف ذائبة للقولون.": "Soluble fibre, good for the gut.",
    "فيتامين A.": "Vitamin A.",
    "فيتامين C وإنزيمات هضم.": "Vitamin C and digestive enzymes.",
    "إنزيم البروميلين للهضم.": "Bromelain, which aids digestion.",
    "دهون صحية — فاكهة استثنائية.": "Healthy fats — an exceptional fruit.",
    "دهون مشبعة نباتية.": "Plant-based saturated fat.",
    "فيتامين C وقلوية.": "Vitamin C, and alkalising.",
    "ملين طبيعي خفيف.": "A gentle natural laxative.",
    "أشهر علاج طبيعي للإمساك.": "The best-known natural remedy for constipation.",
    "سكر مركز وحديد.": "Concentrated sugar, and iron.",
    "رمضاني سكري مركز.": "A Ramadan staple, concentrated in sugar.",
    "مضاد التهابات ومفيد للنقرس.": "Anti-inflammatory, and helpful for gout.",
    "موسمي ومضادات أكسدة.": "Seasonal, and full of antioxidants.",
    "سوبرفود للذاكرة.": "A superfood for memory.",
    "مشهور في أنظمة التخسيس.": "A fixture of weight-loss diets.",
    "حلاوة خريفية عالية.": "Intensely sweet, and autumnal.",
    "مركز جداً.": "Very concentrated.",
    "استوائي حلو.": "Sweet and tropical.",
    "ألياف عالية جداً.": "Very high in fibre.",
    "مرطب صيفي.": "Hydrating in summer.",
    "صيفي شعبي بيهدي السكر.": "A popular summer fruit that steadies blood sugar.",
    "الشربات ضاعف السكر.": "The syrup has doubled the sugar.",
    "فيتامين E ودهون صحية.": "Vitamin E and healthy fats.",
    "أوميجا 3 نباتية للمخ.": "Plant-based omega 3 for the brain.",
    "كارب أعلى من باقي المكسرات.": "Higher in carbs than other nuts.",
    "مفيد للقلب.": "Good for the heart.",
    "أعلى مكسرات بروتيناً مع اللوز.": "Along with almonds, the highest-protein nut.",
    "أرخص مصدر دهون صحية.": "The cheapest source of healthy fats.",
    "زنك ومغنيسيوم — بروتين خرافي.": "Zinc and magnesium, with remarkable protein.",
    "فيتامين E.": "Vitamin E.",
    "كالسيوم نباتي عالي.": "High in plant-based calcium.",
    "عصير السمسم.": "Pressed sesame.",
    "طحينة + سكر كتير.": "Tahini plus a lot of sugar.",
    "أفضل زيت للقلب.": "The best oil for the heart.",
    "زيت القلي الشائع.": "The common frying oil.",
    "أوميجا 3 وألياف هائلة.": "Omega 3 and a huge amount of fibre.",
    "مطحونة عشان تستفيد بيها.": "Grind them or you get no benefit.",
    "خليط الفوائد.": "A mix of all their benefits.",
    "الملح بيخليك متبطلش.": "The salt is what stops you putting them down.",
    "الشامي الفاخر.": "The premium Levantine kind.",
    "أغلى وأدسم المكسرات.": "The most expensive and richest nut.",
    "أعلى مكسرات دهوناً.": "The fattiest nut there is.",
    "أغنى مصدر سيلينيوم.": "The richest source of selenium.",
    "السكوب ≈ 30 جم = 120 سعرة و24 جم بروتين.": "A scoop is roughly 30 g: 120 calories and 24 g of protein.",
    "بطيء الامتصاص.": "Slow to absorb.",
    "للنباتيين وحساسية اللاكتوز.": "For vegetarians and the lactose intolerant.",
    "صفر سعرات — أداء وقوة.": "Zero calories — performance and strength.",
    "اقرأ الملصق — بيتفاوتوا جداً.": "Read the label — they vary enormously.",
    "يستخدم بكميات ضئيلة.": "Used in tiny amounts.",
    "طحلب أعلى بروتين في الطبيعة.": "An algae with the highest protein content in nature.",
    "أوميجا 3 و6 متوازنة.": "A balanced omega 3 to 6 ratio.",
    "فيتامين E وزنك.": "Vitamin E and zinc.",
    "ألياف خارقة للإمساك.": "Exceptional fibre for constipation.",
    "بروتين كولاجيني.": "Collagen protein.",
    "للمفاصل والبشرة.": "For joints and skin.",
    "مضاد حيوي طبيعي ومفيد للقلب.": "A natural antibiotic, and good for the heart.",
    "مضاد التهابات وغثيان.": "Anti-inflammatory, and settles nausea.",
    "الكركمين مضاد التهابات قوي.": "Curcumin, a powerful anti-inflammatory.",
    "بتحسن حساسية الأنسولين.": "Improves insulin sensitivity.",
    "بيهدي القولون والانتفاخ.": "Calms the gut and bloating.",
    "للتتبيلات والتسبيك.": "For marinades and sauce bases.",
    "فيتامين K ونكهة.": "Vitamin K, and flavour.",
    "فيتامين C وحديد ومدر طبيعي.": "Vitamin C, iron, and a natural diuretic.",
    "للسمك والمحاشي.": "For fish and stuffed vegetables.",
    "مهدئ للقولون والمعدة.": "Soothing for the gut and stomach.",
    "مضاد أكسدة عطري.": "An aromatic antioxidant.",
    "مطهر طبيعي للجهاز التنفسي.": "A natural antiseptic for the airways.",
    "منشط للذاكرة والدورة الدموية.": "Stimulates memory and circulation.",
    "على البيتزا والمكرونة.": "On pizza and pasta.",
    "بيحسن الهضم والامتصاص.": "Improves digestion and absorption.",
    "بيرفع الحرق مؤقتاً.": "Raises calorie burn, briefly.",
    "لون ونكهة بدون حرارة.": "Colour and flavour without the heat.",
    "في القهوة العربي.": "In Arabic coffee.",
    "مسكن طبيعي للأسنان.": "A natural toothache remedy.",
    "نكهة دافية للبشاميل.": "A warm flavour for béchamel.",
    "للشوربة والمسلوقات.": "For soups and boiled dishes.",
    "طارد قوي للغازات.": "Strongly relieves wind.",
    "مهدئ ومنوم خفيف.": "Calming, and a mild sleep aid.",
    "مشروب النفاس التقليدي.": "The traditional postnatal drink.",
    "بتزود اللبن للمرضعات.": "Increases milk supply while breastfeeding.",
    "صوص قليل السعرات!": "A low-calorie condiment!",
    "شبه صفر سعرات.": "Almost no calories.",
    "بيساعد على الشبع.": "Helps you feel full.",
    "ملح عالي جداً.": "Very high in salt.",
    "صفر سعرات لكن صوديوم خالص.": "No calories, but pure sodium.",
    "ثلثه سكر تقريباً.": "Roughly a third sugar.",
    "ثلث سعرات العادي.": "A third of the calories of the regular kind.",
    "ليكوبين مركز.": "Concentrated lycopene.",
    "ملح وجلوتامات عالية.": "High in salt and glutamate.",
    "حديد وكالسيوم حقيقيين.": "Genuine iron and calcium.",
    "نكهة بدون سعرات.": "Flavour with no calories.",
    "الكمية المستخدمة ضئيلة.": "The amount used is minuscule.",
    "بروتين وB12 للنباتيين.": "Protein and B12 for vegetarians.",
    "أسهل في التخزين من الطازج.": "Easier to store than fresh.",
    "حامض شامي للسلطات.": "A Levantine souring agent for salads.",
    "أغلى توابل العالم.": "The most expensive spice in the world.",
    "خلطة كل بيت عربي.": "The house blend of every Arab kitchen.",
    "مغربية تونسية حارة.": "A hot Moroccan-Tunisian paste.",
    "سمسم وبندق وكمون.": "Sesame, hazelnut and cumin.",
    "حار حلو.": "Hot and sweet.",
    "سكر أساساً.": "Mostly sugar.",
    "أتقل صوص سلطة.": "The heaviest salad dressing there is.",
    "حلو طبيعي للسلطات.": "Naturally sweet, for salads.",
    "مغربي أصيل.": "Authentically Moroccan.",
    "رفيق السوشي.": "Sushi's companion.",
    "حار ياباني.": "Japanese heat.",
    "ريحان وزيت وصنوبر.": "Basil, oil and pine nuts.",
    "حامض حلو شامي.": "A Levantine sweet-and-sour.",
    "محلي طبيعي.": "A natural sweetener.",
    "محلي طبيعي صفر سعرات.": "A natural zero-calorie sweetener.",
    "صفر سعرات — صديقك الأول.": "Zero calories — your closest ally.",
    "مضادات أكسدة.": "Antioxidants.",
    "بترفع الحرق قليلاً.": "Raises calorie burn slightly.",
    "حسب اللبن والسكر.": "Depends on the milk and the sugar.",
    "الكيس ≈ 90 سعرة سكر ودهون.": "One sachet is about 90 calories of sugar and fat.",
    "الكوب = سكر 3 برتقانات بدون أليافها.": "A glass holds the sugar of 3 oranges without their fibre.",
    "غالباً مضاف له سكر.": "Usually has sugar added.",
    "سكر سريع صافي.": "Pure, fast-releasing sugar.",
    "الكانز = 7 ملاعق سكر.": "A can holds 7 spoons of sugar.",
    "صفر سعرات فعلاً.": "Genuinely zero calories.",
    "لو من غير سكر ممتاز.": "Excellent, as long as it is unsweetened.",
    "جوز هند وسكر.": "Coconut and sugar.",
    "مدر ومنعش.": "A refreshing diuretic.",
    "سكر مضاف عادة.": "Normally has sugar added.",
    "بيخفض الضغط.": "Lowers blood pressure.",
    "بروتين + سكر.": "Protein plus sugar.",
    "كافيين وسكر عالي.": "Caffeine and a lot of sugar.",
    "للمناعة والهضم.": "For immunity and digestion.",
    "أقوى الشاي في مضادات الأكسدة.": "The most antioxidant-rich tea there is.",
    "سادة شبه صفر.": "Taken black, almost no calories.",
    "ثلثه لبن.": "A third of it is milk.",
    "لبن أكتر من الكابتشينو.": "More milk than a cappuccino.",
    "قهوة + شوكولاتة + سكر.": "Coffee plus chocolate plus sugar.",
    "نشا ولبن وسكر.": "Starch, milk and sugar.",
    "شوربة حمص بالكمون والليمون.": "A chickpea broth with cumin and lemon.",
    "مهدئ قبل النوم.": "Calming before bed.",
    "بيتعمل بلبن وسكر.": "Made with milk and sugar.",
    "مشروب النفاس بالسمن والمكسرات.": "The postnatal drink, with ghee and nuts.",
    "حسب المكونات.": "Depends what goes in it.",
    "آيس كريم ولبن وسكر.": "Ice cream, milk and sugar.",
    "فيتامين A وC.": "Vitamins A and C.",
    "مضادات أكسدة عالية.": "High in antioxidants.",
    "غالباً بلبن وسكر في المحلات.": "Shops usually make it with milk and sugar.",
    "سعرات موزة + كوب لبن.": "The calories of a banana plus a glass of milk.",
    "طبقات فواكه وعسل ومكسرات.": "Layers of fruit, honey and nuts.",
    "صفر فعلي.": "Genuinely zero.",
    "إلكتروليتات طبيعية.": "Natural electrolytes.",
    "شاي بحليب مكثف وهيل.": "Tea with condensed milk and cardamom.",
    "بالهيل — شبه صفر.": "With cardamom — almost no calories.",
    "غازي بطعم الشعير.": "A fizzy malt drink.",
    "السكر المضاف هو المشكلة.": "The added sugar is the problem.",
    "سكر بنكهة فواكه.": "Sugar with a fruit flavour.",
    "بدائل حلوة للمياه.": "Sweet alternatives to water.",
    "مضادات أكسدة حقيقية.": "Genuine antioxidants.",
    "سكر أعلى من الدارك.": "More sugar than dark chocolate.",
    "سمنة وشربات.": "Ghee and sugar syrup.",
    "سميد وشربات.": "Semolina and sugar syrup.",
    "عجين ومكسرات وشربات.": "Pastry, nuts and sugar syrup.",
    "عجين ولبن ومكسرات.": "Pastry, milk and nuts.",
    "أخف الحلويات الشرقية.": "The lightest of the Middle Eastern desserts.",
    "نشا ولبن.": "Starch and milk.",
    "أخف تحلية.": "The lightest dessert going.",
    "الكرة = 65-70 جم.": "One scoop = 65-70 g.",
    "البسكوتة ≈ 8 جم = 35 سعرة.": "One biscuit is about 8 g — 35 calories.",
    "الشريحة ≈ 80 جم.": "One slice is roughly 80 g.",
    "زبدة مطوية في عجين.": "Butter folded into pastry.",
    "مقلي + سكر.": "Fried, then sugared.",
    "سكر طبيعي بفوائد.": "Natural sugar, with some benefits.",
    "سكر مركز.": "Concentrated sugar.",
    "سعرات فارغة تماماً.": "Purely empty calories.",
    "سوداني وسكر.": "Peanuts and sugar.",
    "مقلية ومغموسة شربات.": "Fried and soaked in syrup.",
    "رمضانية مقلية بالشربات.": "A Ramadan sweet, fried and syruped.",
    "سمنة ومحشي.": "Ghee and a filling.",
    "سمنة وسكر ودقيق.": "Ghee, sugar and flour.",
    "بسكوت العيد الناعم.": "The delicate Eid biscuit.",
    "شامي خليجي بالعيد.": "Levantine and Gulf, made for Eid.",
    "بالجبن الحلو.": "Made with sweet cheese.",
    "عيش وقشطة وشربات.": "Bread, clotted cream and syrup.",
    "بلح الشام المقلي.": "Fried choux fingers.",
    "بالمكسرات والزبيب.": "With nuts and raisins.",
    "خفيف نسبياً.": "Relatively light.",
    "كريمة وشوكولاتة.": "Cream and chocolate.",
    "جبن كريمي ودهون.": "Cream cheese and fat.",
    "شوكولاتة مركزة.": "Concentrated chocolate.",
    "العجينة + الصوص.": "The batter plus the sauce.",
    "النوتيلا نصها سكر.": "Nutella is half sugar.",
    "سكر منفوش هوا.": "Sugar spun with air.",
    "نشا وسكر.": "Starch and sugar.",
    "سمسم وعسل.": "Sesame and honey.",
    "مكسرات وسكر.": "Nuts and sugar.",
    "سكر وجيلاتين.": "Sugar and gelatin.",
    "أشهر أنواع الشوكولاتة.": "The best-known chocolate there is.",
    "57% سكر.": "57% sugar.",
    "أعلى المربات أليافاً.": "The highest-fibre jam.",
    "سميد وجبن وقشطة.": "Semolina, cheese and clotted cream.",
    "البسكوتة = 30 سعرة.": "One biscuit = 30 calories.",
    "زبدة + جبنة.": "Butter plus cheese.",
    "اسمه مضلل — سعراته عالية.": "The name misleads — they are high in calories.",
    "طبقات كريمة.": "Layers of cream.",
    "سكر خالص.": "Pure sugar.",
    "خصائص مضادة للبكتيريا.": "Antibacterial properties.",
    "ضيافة فاخرة.": "A premium thing to serve guests.",
    "للساندوتش الواحد ≈ 250 جم.": "One wrap is roughly 250 g.",
    "دهون أعلى من الفراخ.": "Higher in fat than the chicken version.",
    "الوجبة كاملة 900-1200 سعرة!": "The full meal runs 900-1200 calories.",
    "القطعة ≈ 100-120 جم.": "One slice is roughly 100-120 g.",
    "اللحوم المصنعة بتزود الدهون.": "The processed meat pushes the fat up.",
    "سمنة بين الطبقات.": "Ghee between the layers.",
    "رز ومكرونة وعدس.": "Rice, pasta and lentils.",
    "فطار الشارع الشهير.": "The famous street breakfast.",
    "بروتين وحديد.": "Protein and iron.",
    "لحمة مفرومة في عيش بالفرن.": "Minced meat baked inside bread.",
    "البانيه مقلي.": "The escalope is deep-fried.",
    "لحم معالج مقلي.": "Processed meat, deep-fried.",
    "6-8 قطع = رول.": "6-8 pieces make one roll.",
    "الكيس الصغير = 160 سعرة.": "A small bag = 160 calories.",
    "لبن ودقيق وزبدة ولحمة.": "Milk, flour, butter and meat.",
    "الأرز والزيت والتسبيكة.": "The rice, the oil and the sauté.",
    "زيت أكتر من العادي.": "More oil than the usual version.",
    "طبق السعودية الأول — رز وفراخ وبهارات.": "Saudi Arabia's signature dish: rice, chicken and spices.",
    "مدخن على الحطب.": "Smoked over wood.",
    "كبسة الخليج بالبهارات اللومي.": "The Gulf kabsa, spiced with dried lime.",
    "لبن جميد دسم.": "Rich fermented jameed yogurt.",
    "رز وباذنجان وفراخ مقلوبة.": "Rice, eggplant and chicken, turned out upside down.",
    "الطبق الشعبي الأشهر.": "The most popular dish of all.",
    "زبادي وحمص وعيش محمص.": "Yogurt, chickpeas and toasted bread.",
    "رز وعيش وصلصة ولحمة.": "Rice, bread, tomato sauce and meat.",
    "بيض في صلصة طماطم.": "Eggs in tomato sauce.",
    "بالباذنجان المشوي أخف 40%.": "With grilled eggplant it is 40% lighter.",
    "طبيخ بيتي متوازن.": "A balanced home-cooked stew.",
    "من أخف الطبيخ المصري.": "One of the lightest Egyptian stews.",
    "أخف من محشي الكرنب.": "Lighter than stuffed cabbage.",
    "يالنجي باللحمة.": "Yalanji, made with meat.",
    "لحمة مفرومة متبلة.": "Seasoned minced meat.",
    "لحمة بالبصل في حلة.": "Meat and onion cooked in a pot.",
    "بالزيتون والليمون المخلل.": "With olives and preserved lemon.",
    "شوربة رمضان المغربية.": "The Moroccan Ramadan soup.",
    "وجبة الشتاء المثالية.": "The perfect winter meal.",
    "خفيفة ومغذية.": "Light and nourishing.",
    "أخف بداية لأي وجبة.": "The lightest way to start any meal.",
    "عدس بجبته ألياف أعلى.": "Whole lentils with their skins: more fibre.",
    "البشاميل بيتقل الطبق.": "The béchamel makes the dish much heavier.",
    "رز باللبن والسمنة في الفرن.": "Rice baked with milk and ghee.",
    "رز بالسمك والبصل المكرمل.": "Rice with fish and caramelised onion.",
    "كريمة وجبن وفراخ.": "Cream, cheese and chicken.",
    "طبقات جبن ولحمة وبشاميل.": "Layers of cheese, meat and béchamel.",
    "هندي خليجي بالبهارات.": "Indian-Gulf, and heavily spiced.",
    "بيتزا الشام.": "The Levantine pizza.",
    "فطار شامي.": "A Levantine breakfast.",
    "رمضانية مقلية.": "A fried Ramadan staple.",
    "مقلية برضو.": "Also deep-fried.",
    "برغل ولحمة مقلية.": "Bulgur and meat, deep-fried.",
    "برغل وبقدونس وزيت.": "Bulgur, parsley and oil.",
    "العيش المحمص هو الزيادة.": "The fried bread is where the extra calories are.",
    "مبردة ومهضمة.": "Cooling, and easy to digest.",
    "بطحينة أكتر من المصري.": "More tahini than the Egyptian version.",
    "بروتين ممتاز جاهز.": "Excellent protein, ready to go.",
    "مقلية بضغط.": "Pressure-fried.",
    "القشرة نصف السعرات.": "The coating is half the calories.",
    "لحم معالج.": "Processed meat.",
    "مكسيكي.": "Mexican.",
    "بروتين أنضف من الساندوتش.": "Cleaner protein than the sandwich.",
    "تركي يوناني.": "Turkish and Greek.",
    "مخبوزة أفضل من كتير.": "Baked, which beats plenty of the alternatives.",
    "قارب تركي بالجبن.": "A Turkish cheese boat.",
    "بالجبنة والصوصات بيتقل.": "The cheese and sauces make it heavy.",
    "طبيخ بيتي مشبع.": "A filling home-cooked tray.",
    "سريعة ومتوازنة.": "Quick and balanced.",
    "الصوص والكراتون هما الفخ.": "The dressing and croutons are the trap.",
    "بروتين خفيف.": "Light protein.",
    "مقلي في عجينة.": "Deep-fried in batter.",
    "الدبل يعني دبل كل حاجة.": "Double means double of everything.",
    "أسمك من الشيبسي بس مقلية.": "Thicker than crisps, but still fried.",
    "عجينة تشرب زيت.": "Batter that drinks up oil.",
    "زبدة وثوم على عيش.": "Butter and garlic on bread.",
    "مقرمشات وجبن سايح.": "Crisps and melted cheese.",
    "فطار البطل المصري.": "The Egyptian breakfast of champions.",
    "طبقات بالسمنة والجبن.": "Layers of ghee and cheese.",
    "ساندوتش المدرسة الكلاسيكي.": "The classic school sandwich.",
    "طاقة سريعة جداً.": "Very fast energy.",
    "هوا وزيت وملح.": "Air, oil and salt.",
    "أخف من المقلية بثلث.": "A third lighter than the fried kind.",
    "الكريمة هي التقل.": "The cream is what weighs it down.",
    "خفيفة ودافية.": "Light and warming.",
    "بروتين بحري خفيف.": "Light seafood protein.",
}

TIPS_EN = {
    # ── poultry ──
    "💡 أفضل طريقة: شوي أو بخار.": "💡 Best cooked grilled or steamed.",
    "💡 اشيل الجلد لتقليل الدهون.": "💡 Remove the skin to cut the fat.",
    "💡 في الفرن أفضل من القلي.": "💡 Oven-baked beats fried.",
    "💡 ممتاز للكفتة الدايت.": "💡 Great for diet kofta.",
    "⚠️ ممنوعة للحامل وأمراض الكلى.": "⚠️ Not for pregnancy or kidney disease.",
    "💡 مسلوقة أفضل.": "💡 Better boiled.",
    "💡 ممتاز للتخسيس.": "💡 Excellent for weight loss.",
    "💡 شيل الجلد دايماً.": "💡 Always remove the skin.",
    "💡 مشوي في الفرن.": "💡 Roast it in the oven.",
    "💡 من غير الحشو أخف بكتير.": "💡 Much lighter without the stuffing.",
    # ── meat ──
    "💡 الحصة المناسبة 150-200g.": "💡 A sensible portion is 150-200g.",
    "💡 ممتاز للبرجر والكفتة.": "💡 Great for burgers and kofta.",
    "⚠️ قلله في التخسيس.": "⚠️ Cut back on it while losing weight.",
    "💡 مثالي للستيك الصحي.": "💡 Ideal for a healthy steak.",
    "⚠️ قلل الكمية لو عندك كوليسترول.": "⚠️ Reduce the amount if your cholesterol is high.",
    "💡 بديل صحي في الخليج.": "💡 A healthy Gulf alternative.",
    "⚠️ مرة أسبوعياً كحد أقصى.": "⚠️ Once a week at most.",
    "⚠️ دهونه مش قليلة.": "⚠️ It is not low in fat.",
    "⚠️ سعرات ودهون عالية.": "⚠️ High in calories and fat.",
    "⚠️ مقلي بيبقى أتقل.": "⚠️ Fried, it gets much heavier.",
    "⚠️ قلل الاستهلاك.": "⚠️ Keep intake down.",
    "💡 اعمل برجر بيتي أفضل.": "💡 Making your own burger is better.",
    "⚠️ مرات قليلة في الشهر.": "⚠️ Only a few times a month.",
    "⚠️ ممنوعة لمرضى الضغط.": "⚠️ Not for people with high blood pressure.",
    "💡 للأطفال والكبار.": "💡 Suits children and adults.",
    "💡 مسلوقة شوربتها غنية.": "💡 Boiled, it makes a rich broth.",
    "⚠️ الدهن الظاهر شيله قبل الشوي.": "⚠️ Trim the visible fat before grilling.",
    "⚠️ ممنوعة للنقرس.": "⚠️ Not for gout.",
    "💡 مشوية في السيخ.": "💡 Grilled on skewers.",
    "⚠️ مرات نادرة فقط.": "⚠️ Only on rare occasions.",
    "⚠️ شرائح قليلة نادرة.": "⚠️ A few slices, rarely.",
    "⚠️ ملح عالي جداً.": "⚠️ Very high in salt.",
    # ── fish ──
    "💡 الأنسب للتخسيس.": "💡 The best fit for weight loss.",
    "💡 مرتين أسبوعياً مفيد للقلب.": "💡 Twice a week is good for the heart.",
    "💡 اختار بالماء مش الزيت.": "💡 Choose the one in water, not oil.",
    "💡 صفّي الزيت كويس.": "💡 Drain the oil well.",
    "💡 ممتاز للعظام.": "💡 Excellent for the bones.",
    "💡 مشوي أو فرن.": "💡 Grilled or oven-baked.",
    "💡 فرن بالليمون.": "💡 Oven-baked with lemon.",
    "💡 شوي أو فرن.": "💡 Grill or oven-bake.",
    "💡 تجنبه مقلي.": "💡 Avoid it fried.",
    "⚠️ يحتوي كوليسترول — اعتدل.": "⚠️ Contains cholesterol, so go easy.",
    "💡 مسلوقة أخف.": "💡 Lighter boiled.",
    "⚠️ مقلي بيتضاعف 3 مرات.": "⚠️ Fried, it triples.",
    "💡 مسلوق بالليمون.": "💡 Boiled with lemon.",
    "💡 في الفرن بالبهارات.": "💡 In the oven with spices.",
    "⚠️ ممنوعة للضغط والكلى.": "⚠️ Not for blood pressure or kidney problems.",
    "⚠️ خطر على الضغط — كميات صغيرة جداً.":
        "⚠️ Risky for blood pressure, so very small amounts only.",
    "💡 سريع التسوية.": "💡 Cooks quickly.",
    "⚠️ للضغط: نادراً.": "⚠️ For high blood pressure: rarely.",
    "⚠️ ينقع 24 ساعة قبل الطبخ.": "⚠️ Soak for 24 hours before cooking.",
    "💡 مطهي كويس دايماً.": "💡 Always cook it thoroughly.",
    "💡 مثالي للأطفال وكبار السن.": "💡 Ideal for children and older adults.",
    "💡 مشوية نص تسوية.": "💡 Grilled medium-rare.",
    "💡 صفي الزيت.": "💡 Drain the oil.",
    "💡 بديل ذكي للطازج الغالي.": "💡 A smart substitute for pricey fresh fish.",
    "💡 على مكرونة أو سلطة.": "💡 On pasta or salad.",
    "⚠️ صوديوم أعلى من الطازج.": "⚠️ Higher in sodium than fresh.",
    "⚠️ للأطفال: قللها.": "⚠️ For children: cut it down.",
    "💡 في الفرن مش القلاية.": "💡 In the oven, not the fryer.",
    "💡 مشوحة بملعقة زيت أفضل.": "💡 Better pan-tossed in a spoon of oil.",
    "💡 أفضل اختيار للساندوتشات الباردة.": "💡 The best choice for cold sandwiches.",
    "💡 مشوي مش مقلي.": "💡 Grilled, not fried.",
    "💡 2-3 بيضات يومياً آمن.": "💡 2-3 eggs a day is safe.",
    "💡 الأنسب لكمال الأجسام.": "💡 The best fit for bodybuilding.",
    "💡 مفيد باعتدال.": "💡 Good for you in moderation.",
    "💡 كوب = 240 مل.": "💡 One cup = 240 ml.",
    "💡 الأفضل في التخسيس.": "💡 The best choice while losing weight.",
    "💡 علبة = 100-120 جم.": "💡 One pot = 100-120 g.",
    "💡 ممتاز كسناك.": "💡 Excellent as a snack.",
    "💡 ممتاز قبل النوم.": "💡 Excellent before bed.",
    "💡 ممتاز بعد الأكل الدسم.": "💡 Excellent after a rich meal.",
    "💡 خفيف وممتاز للفطار.": "💡 Light and great for breakfast.",
    "⚠️ ملح عالي — قلل الكمية.": "⚠️ High in salt, so keep the amount down.",
    "💡 اختيار كويس للدايت.": "💡 A good pick for a diet.",
    "💡 نسخة قليلة الدسم أفضل.": "💡 The low-fat version is better.",
    "⚠️ 30 جم كفاية كحصة.": "⚠️ 30 g is enough for a portion.",
    "⚠️ قطعة واحدة كفاية.": "⚠️ One triangle is enough.",
    "⚠️ اشطفها قبل الشوي.": "⚠️ Rinse it before grilling.",
    "💡 بزيت زيتون على الفطار.": "💡 With olive oil at breakfast.",
    "⚠️ ملعقة صغيرة تكفي.": "⚠️ A teaspoon is plenty.",
    "⚠️ ملعقة صغيرة = 100 سعرة.": "⚠️ A teaspoon = 100 calories.",
    "⚠️ استخدم أقل كمية ممكنة.": "⚠️ Use as little as you can.",
    "💡 بزيت زيتون وليمون — فطار مثالي.": "💡 With olive oil and lemon — the perfect breakfast.",
    "💡 قلل الزيت لو بتخس.": "💡 Go easy on the oil if you are losing weight.",
    "💡 بالليمون يمتص الحديد أفضل.": "💡 With lemon, the iron absorbs better.",
    "💡 بالأرز = بروتين متكامل.": "💡 With rice it makes a complete protein.",
    "💡 حمص الشام سناك دافي.": "💡 Balila makes a warming snack.",
    "💡 3 ملاعق حصة معقولة.": "💡 3 tablespoons is a sensible portion.",
    "💡 بالصلصة أكلة كاملة.": "💡 In tomato sauce it is a whole meal.",
    "💡 بديل جيد للفاصوليا.": "💡 A good substitute for white beans.",
    "💡 بالجزر طبق كلاسيكي خفيف.": "💡 With carrots, a light classic.",
    "💡 سناك مثالي — بس مملح.": "💡 A perfect snack, but salty.",
    "⚠️ في الفرن أو القلاية الهوائية أخف.": "⚠️ Lighter in the oven or an air fryer.",
    "⚠️ 30 جم = 170 سعرة.": "⚠️ 30 g = 170 calories.",
    "💡 ملعقة كبيرة = 95 سعرة.": "💡 One tablespoon = 95 calories.",
    "💡 سناك ياباني صحي.": "💡 A healthy Japanese snack.",
    "💡 بياخد طعم التتبيلة.": "💡 It takes on whatever you marinate it in.",
    "⚠️ 30 جم كحد أقصى.": "⚠️ 30 g at most.",
    "💡 اشطفها تقلل الملح.": "💡 Rinsing it cuts the salt.",
    "⚠️ ملحها عالي جداً.": "⚠️ Very high in salt.",
    "⚠️ الملح عالي — للضغط لأ.": "⚠️ High in salt — not for high blood pressure.",
    "💡 وفرت ربع السعرات.": "💡 Saves a quarter of the calories.",
    "⚠️ للطبخ بكميات صغيرة.": "⚠️ For cooking, in small amounts.",
    "💡 مثالي للكيتو واللاكتوز.": "💡 Ideal for keto and lactose intolerance.",
    "💡 اختار غير المحلى.": "💡 Choose the unsweetened kind.",
    "💡 معلقة كبيرة = 45 سعرة.": "💡 One tablespoon = 45 calories.",
    "💡 مشروب تركي مرطب.": "💡 A hydrating Turkish drink.",
    "💡 بالكمون والليمون شتوي أصيل.": "💡 With cumin and lemon, a proper winter dish.",
    "💡 التقلية على الوش هي الزيادة.": "💡 The fried garlic topping is where the extra calories are.",
    "💡 وجبة متكاملة بمعايير عالية.": "💡 A complete meal by any standard.",
    "💡 تُطهى جيداً دائماً.": "💡 Always cook them thoroughly.",
    "💡 بوريتو صحي.": "💡 A healthy burrito.",
    "💡 بالخضار بدل الجبن أخف.": "💡 Vegetables instead of cheese is lighter.",
    "💡 بيضة مسلوقة = 78 سعرة بس.": "💡 A boiled egg is only 78 calories.",
    "💡 زبادي سادة + فاكهة طازجة أفضل.": "💡 Plain yogurt with fresh fruit is better.",
    "💡 قطعة في ساندوتش المدرسة.": "💡 One triangle in a school sandwich.",
    "💡 اشطفه يقل الملح.": "💡 Rinsing it cuts the salt.",
    "💡 اشطفه دايماً.": "💡 Always rinse it.",
    "💡 اقرأ الملصق.": "💡 Read the label.",
    "💡 كوب مطبوخ ≈ 160 جم.": "💡 One cooked cup is roughly 160 g.",
    "💡 أفضل لمرضى السكر.": "💡 Better for people with diabetes.",
    "💡 اختيار كويس باعتدال.": "💡 A good choice in moderation.",
    "💡 اسلقها الدنتة أفضل للسكر.": "💡 Cooked al dente it is better for blood sugar.",
    "💡 بتشبع أكتر.": "💡 More filling.",
    "💡 نص رغيف = حصة نشويات.": "💡 Half a loaf is one starch portion.",
    "⚠️ سريع الامتصاص.": "⚠️ Absorbed quickly.",
    "💡 الأفضل للدايت والسكر.": "💡 The best pick for dieting and diabetes.",
    "💡 محمص بيبقى أخف على المعدة.": "💡 Toasted, it sits lighter.",
    "💡 اختيارك الأول.": "💡 Your first choice.",
    "💡 40-50 جم حصة مثالية.": "💡 40-50 g is the ideal portion.",
    "⚠️ اختار الأنواع بدون سكر.": "⚠️ Choose the unsweetened kinds.",
    "💡 بديل ذكي للأرز.": "💡 A smart swap for rice.",
    "💡 بالخضار وجبة كاملة.": "💡 With vegetables it is a full meal.",
    "💡 ممتاز للشوربة.": "💡 Excellent in soup.",
    "💡 غالية بس تستاهل.": "💡 Pricey, but worth it.",
    "💡 مسلوقة مش مقلية!": "💡 Boiled, not fried.",
    "⚠️ في الفرن بشوية زيت أفضل.": "⚠️ Better in the oven with a little oil.",
    "💡 في الفرن ألذ وأصح.": "💡 Tastier and healthier in the oven.",
    "💡 من غير زبدة وملح كتير.": "💡 Without much butter or salt.",
    "💡 اخلطه بدقيق أسمر.": "💡 Blend it with wholemeal flour.",
    "💡 حمصها من غير سمنة كتير.": "💡 Toast it without much ghee.",
    "⚠️ مش أكل منتظم.": "⚠️ Not an everyday food.",
    "💡 بمعلقة زيت صغيرة أخف.": "💡 Lighter with a small spoon of oil.",
    "💡 البيضاء ضعفها سعرات.": "💡 The white sauce has twice the calories.",
    "💡 جيب الرغيف يتحشى سلطة.": "💡 Stuff the pocket with salad.",
    "💡 اختار القمح الكامل.": "💡 Choose the whole-wheat one.",
    "💡 نص رغيف حصة.": "💡 Half a loaf is one portion.",
    "💡 خيار خليجي صحي.": "💡 A healthy Gulf option.",
    "💡 رقاقة باللحمة المفرومة تحسب.": "💡 A sheet with minced meat counts as a meal.",
    "💡 اطلب Thin دايماً.": "💡 Always order thin crust.",
    "💡 الحبوب الكاملة أفضل للسكر.": "💡 Whole grains are better for blood sugar.",
    "⚠️ نصف كوب = 230 سعرة.": "⚠️ Half a cup = 230 calories.",
    "💡 مثل الأبيض تماماً غذائياً.": "💡 Nutritionally identical to white rice.",
    "💡 للسلطات الآسيوية.": "💡 For Asian salads.",
    "💡 أذكى سناك سينما — من غير زبدة.": "💡 The smartest cinema snack, as long as it is butter-free.",
    "⚠️ كيس السينما الكبير = 1000+ سعرة.": "⚠️ A large cinema tub is over 1000 calories.",
    "💡 بالمكسرات وعسل قليل.": "💡 With nuts and a little honey.",
    "💡 قطعة بالجبنة القريش فطار خفيف.": "💡 A piece with cottage cheese makes a light breakfast.",
    "💡 حسب إرشادات طبيب الأطفال.": "💡 Follow your paediatrician's guidance.",
    "💡 بحليب خالي الدسم أخف.": "💡 Lighter made with skim milk.",
    "💡 كل براحتك — سعرات لا تذكر.": "💡 Eat freely — the calories are negligible.",
    "💡 مطبوخة الليكوبين أعلى.": "💡 Cooked, the lycopene is higher.",
    "💡 أساس أي سلطة.": "💡 The base of any salad.",
    "💡 مع السمك تقليد مصري صح.": "💡 With fish, a proper Egyptian tradition.",
    "💡 مطبوخة تاكل كمية أكبر.": "💡 Cooked, you can eat far more of it.",
    "💡 قلل التقلية والسعرات تنزل.": "💡 Go easy on the fried garlic topping and the calories drop.",
    "💡 بديل المكرونة (نودلز كوسة).": "💡 A pasta substitute (courgetti).",
    "⚠️ مشوي مش مقلي!": "⚠️ Grilled, not fried!",
    "💡 ني في السلطة أفضل.": "💡 Best raw in a salad.",
    "💡 سناك مقرمش صحي.": "💡 A healthy, crunchy snack.",
    "💡 بخار 5 دقايق يحافظ عليه.": "💡 Five minutes of steaming preserves it.",
    "⚠️ مقلي بيبقى قنبلة سعرات.": "⚠️ Fried, it becomes a calorie bomb.",
    "💡 محشي كرنب: احسب الأرز.": "💡 Stuffed cabbage: count the rice.",
    "💡 بالصلصة من غير لحمة دايت ممتاز.": "💡 In tomato sauce without meat, an excellent diet dish.",
    "💡 سوتيه بالتوم لذيذة.": "💡 Delicious sautéed with garlic.",
    "💡 أساس كل طبخة.": "💡 The base of every dish.",
    "💡 الكمية المستخدمة صغيرة.": "💡 The amount you actually use is tiny.",
    "💡 عصير بنجر قبل التمرين.": "💡 Beetroot juice before training.",
    "💡 مع الفول تقليد صحي.": "💡 With ful, a healthy tradition.",
    "💡 سوتيه مع الفراخ.": "💡 Sautéed with chicken.",
    "💡 احشيها تونة وخضار.": "💡 Fill it with tuna and vegetables.",
    "💡 10 أصابع ≈ 250 سعرة.": "💡 10 rolls is roughly 250 calories.",
    "⚠️ الصوصات ممكن تضاعفها 10 مرات.": "⚠️ Dressings can multiply it tenfold.",
    "💡 ملعقتين كفاية.": "💡 Two tablespoons is enough.",
    "💡 أخف من الحمص.": "💡 Lighter than hummus.",
    "💡 عيدان بالحمص سناك.": "💡 Sticks with hummus make a snack.",
    "💡 في الشوربة.": "💡 In soup.",
    "💡 بالسلق والشوربة — احسبه نشويات.": "💡 Boiled or in soup — count it as a starch.",
    "💡 شوربة قرع شتوية.": "💡 A winter squash soup.",
    "💡 بالفرن بالقرفة تحلية دايت.": "💡 Baked with cinnamon, a diet dessert.",
    "⚠️ للضغط: قطعة واحدة.": "⚠️ For blood pressure: one piece.",
    "⚠️ الضغط والكلى: ابعد.": "⚠️ Blood pressure and kidney problems: stay away.",
    "💡 5-6 حبات حصة.": "💡 5-6 pieces is a portion.",
    "💡 على السلطة بحساب.": "💡 On salad, but counted.",
    "💡 إضافة خارقة للسلطة.": "💡 An outstanding salad addition.",
    "💡 مشوي بالفرن بيبقى سكري الطعم.": "💡 Roasted, it turns sweet.",
    "💡 سوتيه دقايق بس.": "💡 Sauté for a few minutes only.",
    "💡 مشوي من غير زبدة.": "💡 Grilled, without butter.",
    "⚠️ للقولون والقرحة: لأ.": "⚠️ For IBS or ulcers: no.",
    "💡 كوب كامل = 27 سعرة بس.": "💡 A whole cup is only 27 calories.",
    "💡 تحلية ووجبة في واحد.": "💡 Dessert and a meal in one.",
    "💡 بدون سكر مضاف اختار.": "💡 Choose the no-added-sugar kind.",
    "⚠️ الملح أعلى من العادي.": "⚠️ Saltier than the plain kind.",
    "💡 اشطفه من محلول الملح.": "💡 Rinse off the brine.",
    "💡 على السلطات والساندوتشات.": "💡 On salads and sandwiches.",
    "💡 3-4 قطع كفاية.": "💡 3-4 pieces is enough.",
    "💡 في الشوربة والسلق.": "💡 In soup, or boiled.",
    "💡 للكول سلو بزبادي.": "💡 For coleslaw made with yogurt.",
    "💡 أساس البرجر الصحي.": "💡 The base of a healthy burger.",
    "💡 للسيزر الدايت.": "💡 For a lighter Caesar salad.",
    "💡 عملي وسعره ثابت.": "💡 Convenient, and the price stays steady.",
    "💡 من غير تسبيك تقيل.": "💡 Without a heavy roux.",
    "💡 بشوربة فراخ وجبة.": "💡 With chicken soup it is a meal.",
    "💡 من غير سكر مضاف.": "💡 With no added sugar.",
    "💡 بالزبادي تحلية مثالية.": "💡 With yogurt, the perfect dessert.",
    "💡 بديل الآيس كريم المخفوق.": "💡 A stand-in for soft-serve ice cream.",
    "💡 بالقشر الألياف أعلى.": "💡 With the skin on, more fibre.",
    "💡 مثالي قبل التمرين.": "💡 Ideal before training.",
    "💡 الثمرة أفضل من العصير.": "💡 The whole fruit beats the juice.",
    "💡 2-3 حبات حصة.": "💡 2-3 pieces is a portion.",
    "⚠️ كوب واحد كفاية للسكري.": "⚠️ One cup is the limit if you have diabetes.",
    "💡 شريحة كبيرة براحتك.": "💡 A big slice is fine.",
    "💡 سناك صيفي مثالي.": "💡 The perfect summer snack.",
    "💡 نص ثمرة حصة معقولة.": "💡 Half a fruit is a sensible portion.",
    "💡 مسموحة حتى في الكيتو بكميات.": "💡 Allowed even on keto, in measured amounts.",
    "💡 3 حبات كفاية.": "💡 3 pieces is enough.",
    "⚠️ حبتين = ملعقتين سكر.": "⚠️ Two pieces = two spoons of sugar.",
    "💡 التين المجفف سعراته 3 أضعاف.": "💡 Dried figs have three times the calories.",
    "💡 الحبوب أفضل من العصير.": "💡 The seeds beat the juice.",
    "💡 بالقشر أفضل.": "💡 Better with the skin on.",
    "💡 لطيفة على المعدة.": "💡 Gentle on the stomach.",
    "💡 سناك ممتاز.": "💡 An excellent snack.",
    "💡 قمر الدين المجفف سكره عالي.": "💡 Dried apricot leather is high in sugar.",
    "💡 بعد الوجبات الدسمة.": "💡 After a rich meal.",
    "💡 طازج مش معلب بالشربات.": "💡 Fresh, not tinned in syrup.",
    "💡 نص ثمرة يومياً ممتاز للقلب.": "💡 Half a fruit a day is excellent for the heart.",
    "⚠️ سعرات عالية — قطعة صغيرة.": "⚠️ High in calories — a small piece.",
    "💡 على السلطة بدل الصوص.": "💡 On salad instead of dressing.",
    "💡 القراصيا (المجفف) أقوى للإمساك.": "💡 Dried prunes work harder on constipation.",
    "💡 3 حبات منقوعة صباحاً.": "💡 3 soaked prunes in the morning.",
    "💡 ملعقة على الشوفان كفاية.": "💡 A spoonful on your oats is enough.",
    "⚠️ الكوب المحلى = 250+ سعرة.": "⚠️ A sweetened cup is over 250 calories.",
    "💡 كوب = 90 سعرة.": "💡 One cup = 90 calories.",
    "💡 اتبسط في موسمه.": "💡 Enjoy it while it is in season.",
    "💡 كوب يومياً لو متاح.": "💡 A cup a day if you can get them.",
    "⚠️ بيتعارض مع أدوية — اسأل طبيبك.": "⚠️ Interacts with some medicines — ask your doctor.",
    "💡 ثمرة واحدة كفاية.": "💡 One fruit is enough.",
    "⚠️ ملعقة للتزيين فقط.": "⚠️ A spoonful as a garnish only.",
    "💡 على الزبادي والعصائر.": "💡 On yogurt and in juices.",
    "💡 شرائح براحتك تقريباً.": "💡 Slices, more or less freely.",
    "💡 اختار المعلب بالعصير الطبيعي.": "💡 Choose the kind tinned in natural juice.",
    "💡 10-12 حبة حصة مثالية.": "💡 10-12 nuts is the ideal portion.",
    "💡 3-4 حبات يومياً.": "💡 3-4 a day.",
    "💡 10 حبات كفاية.": "💡 10 is enough.",
    "💡 حفنة صغيرة.": "💡 A small handful.",
    "💡 التقشير بيبطئ الأكل — ميزة!": "💡 Shelling them slows you down — which is a feature.",
    "⚠️ المملح يرفع الضغط.": "⚠️ The salted kind raises blood pressure.",
    "💡 30 جم سناك ممتاز.": "💡 30 g makes an excellent snack.",
    "💡 اتسلى بحساب.": "💡 Snack on them, but count them.",
    "💡 على السلطة والزبادي.": "💡 On salad and yogurt.",
    "💡 ملعقة كبيرة = 90 سعرة.": "💡 One tablespoon = 90 calories.",
    "⚠️ قطعة صغيرة = 150 سعرة.": "⚠️ A small piece = 150 calories.",
    "💡 ملعقة كبيرة = 120 سعرة.": "💡 One tablespoon = 120 calories.",
    "💡 للطهي بحرارة عالية.": "💡 For high-heat cooking.",
    "⚠️ متعيدش استخدامه بعد القلي.": "⚠️ Do not reuse it after frying.",
    "💡 ملعقة في الزبادي تشبع ساعات.": "💡 A spoonful in yogurt keeps you full for hours.",
    "💡 ملعقة يومياً للقولون.": "💡 A spoonful a day for the gut.",
    "💡 حفنة 30 جم = 180 سعرة.": "💡 A 30 g handful = 180 calories.",
    "⚠️ للضغط: النيء أفضل.": "⚠️ For blood pressure: raw is better.",
    "💡 بقشره أبطأ في الأكل.": "💡 In the shell, you eat them slower.",
    "💡 رشة على الفتة والمحاشي.": "💡 A sprinkle over fatteh and stuffed vegetables.",
    "💡 5 حبات = 90 سعرة.": "💡 5 nuts = 90 calories.",
    "💡 حبتين يومياً كفاية وزيادة.": "💡 Two a day is more than enough.",
    "💡 بعد التمرين بمياه أو لبن خالي.": "💡 After training, with water or skim milk.",
    "💡 قبل النوم لبناء العضل.": "💡 Before bed, for muscle building.",
    "💡 اخلطه بموز يتحسن طعمه.": "💡 Blend it with banana to improve the taste.",
    "💡 5 جم يومياً بانتظام.": "💡 5 g a day, consistently.",
    "⚠️ بعضها شوكولاتة متنكرة.": "⚠️ Some are chocolate bars in disguise.",
    "💡 معلقة صغيرة صباحاً.": "💡 A teaspoon in the morning.",
    "💡 معلقة في العصير.": "💡 A spoonful in a juice.",
    "💡 ملعقة على السلطة.": "💡 A spoonful on salad.",
    "💡 ملعقة على أي أكل.": "💡 A spoonful on anything.",
    "💡 للجيلي البيتي الدايت.": "💡 For homemade diet jelly.",
    "💡 سكوب في أي مشروب.": "💡 A scoop in any drink.",
    "💡 الفص ≈ 3 جم = 4 سعرات فقط.": "💡 A clove is about 3 g — only 4 calories.",
    "💡 شريحة في الشاي أو الأكل.": "💡 A slice in your tea or your food.",
    "💡 مع فلفل أسود يتضاعف امتصاصه.": "💡 With black pepper, absorption doubles.",
    "💡 نص معلقة يومياً مفيدة للسكري.": "💡 Half a teaspoon a day helps with diabetes.",
    "💡 مغلي الكمون بعد الأكل.": "💡 Cumin tea after eating.",
    "💡 مع الكمون توليفة مصرية.": "💡 With cumin, a classic Egyptian pairing.",
    "💡 على الشوربة والسلطات.": "💡 On soups and salads.",
    "💡 مغلي البقدونس للكلى.": "💡 Parsley tea for the kidneys.",
    "💡 طارد للغازات.": "💡 Relieves wind.",
    "💡 في الشاي أو على السلطة.": "💡 In tea, or on salad.",
    "💡 مع الطماطم توليفة إيطالية.": "💡 With tomato, the Italian pairing.",
    "💡 زعتر بزيت زيتون فطار شامي.": "💡 Zaatar with olive oil, a Levantine breakfast.",
    "💡 مع الفراخ والبطاطس في الفرن.": "💡 With chicken and potatoes in the oven.",
    "💡 مضاد بكتيريا قوي.": "💡 A strong antibacterial.",
    "💡 طازج الطحن أقوى نكهة.": "💡 Freshly ground has far more flavour.",
    "⚠️ ممنوع للقولون والقرحة.": "⚠️ Not for IBS or ulcers.",
    "💡 على الفراخ والبطاطس.": "💡 On chicken and potatoes.",
    "💡 منعش للنفس وهاضم.": "💡 Freshens the breath and aids digestion.",
    "💡 حبة في الشاي كفاية.": "💡 One clove in your tea is enough.",
    "⚠️ كميات كبيرة سامة — رشة بس.": "⚠️ Toxic in large amounts — a pinch only.",
    "💡 يتشال قبل التقديم.": "💡 Remove before serving.",
    "💡 مغلي الشمر للرضع والكبار.": "💡 Fennel tea, for infants and adults.",
    "💡 كوب قبل النوم.": "💡 A cup before bed.",
    "💡 مفيدة للرضاعة.": "💡 Helpful while breastfeeding.",
    "💡 مغلية بعسل — بس سعراتها تتحسب.": "💡 Brewed with honey — but count the calories.",
    "💡 بديل ذكي للمايونيز.": "💡 A smart swap for mayonnaise.",
    "💡 للسلطة والتتبيل براحتك.": "💡 Use it freely on salad and in marinades.",
    "💡 ملعقة في مياه قبل الأكل.": "💡 A spoonful in water before eating.",
    "⚠️ لمرضى الضغط: النسخة قليلة الصوديوم.": "⚠️ For high blood pressure: the low-sodium version.",
    "⚠️ الحد اليومي: معلقة صغيرة (5 جم) للكل.": "⚠️ The daily limit is one teaspoon (5 g), for everyone.",
    "⚠️ ملعقة كبيرة = 17 سعرة.": "⚠️ One tablespoon = 17 calories.",
    "⚠️ ملعقة كبيرة = 94 سعرة!": "⚠️ One tablespoon = 94 calories!",
    "💡 لو مصمم على المايونيز.": "💡 If you insist on mayonnaise.",
    "💡 أساس التسبيكة المصرية.": "💡 The base of the Egyptian tomato sauté.",
    "⚠️ استبدلها ببهارات طبيعية.": "⚠️ Replace them with real spices.",
    "💡 ملعقة على الطحينة — فطار بلدي.": "💡 A spoonful over tahini — a local breakfast.",
    "💡 للحلويات والمشروبات.": "💡 For desserts and drinks.",
    "💡 نقطة كفاية.": "💡 A drop is enough.",
    "💡 رشة على السلطة بطعم الجبن.": "💡 A sprinkle on salad, with a cheesy taste.",
    "💡 في الشاي والمخبوزات.": "💡 In tea and baking.",
    "💡 على الفتوش أساسي.": "💡 Essential on fattoush.",
    "💡 شعرات قليلة تكفي.": "💡 A few threads is plenty.",
    "💡 اعملها في البيت أنقى.": "💡 Made at home it is purer.",
    "⚠️ للقولون: ابعد.": "⚠️ For IBS: stay away.",
    "💡 بالعيش والزيت — احسب الكمية.": "💡 With bread and oil — watch the amount.",
    "⚠️ فيه سكر — والقولون يبعد.": "⚠️ Contains sugar, and not for IBS.",
    "⚠️ ملعقة كبيرة = 29 سعرة.": "⚠️ One tablespoon = 29 calories.",
    "⚠️ ملعقتين = 145 سعرة.": "⚠️ Two tablespoons = 145 calories.",
    "💡 مع زيت زيتون الصوص الأذكى.": "💡 With olive oil, the smartest dressing there is.",
    "⚠️ ملح عالي.": "⚠️ High in salt.",
    "💡 منظف للفم بين الأصناف.": "💡 Cleanses the palate between pieces.",
    "💡 كمية ضئيلة تكفي.": "💡 A tiny amount is enough.",
    "⚠️ ملعقة كبيرة = 80 سعرة.": "⚠️ One tablespoon = 80 calories.",
    "💡 معلقة صغيرة على السلطة.": "💡 A teaspoon on salad.",
    "💡 بديل السكر بحساب.": "💡 A sugar substitute, in measured amounts.",
    "💡 الأفضل لمرضى السكر.": "💡 The best option for diabetics.",
    "💡 8 أكواب يومياً.": "💡 8 glasses a day.",
    "💡 كل معلقة سكر = 20 سعرة.": "💡 Every spoon of sugar = 20 calories.",
    "💡 قبل التمرين بساعة.": "💡 An hour before training.",
    "💡 لبن خالي الدسم أخف.": "💡 Skim milk is lighter.",
    "⚠️ اعمله بنفسك أوفر وأصح.": "⚠️ Making it yourself is cheaper and healthier.",
    "💡 كل البرتقانة أفضل.": "💡 Eating the orange is better.",
    "⚠️ الكوب ممكن يعدي 200 سعرة.": "⚠️ A glass can top 200 calories.",
    "⚠️ كوب صغير لو ضروري.": "⚠️ A small glass, if you must.",
    "⚠️ صفر فايدة غذائية.": "⚠️ No nutritional value whatsoever.",
    "💡 مقبول باعتدال.": "💡 Fine in moderation.",
    "💡 اطلبه من غير سكر.": "💡 Ask for it without sugar.",
    "⚠️ كوب رمضاني = 200+ سعرة.": "⚠️ A Ramadan glass is over 200 calories.",
    "⚠️ ممنوع نهائياً لمرضى الضغط!": "⚠️ Absolutely not for anyone with high blood pressure.",
    "💡 اعمله في البيت بسكر أقل.": "💡 Make it at home with less sugar.",
    "💡 من غير سكر = صفر تقريباً.": "💡 Unsweetened, it is close to zero.",
    "💡 بعد التمرين مقبول.": "💡 Fine after training.",
    "⚠️ مش بديل للنوم.": "⚠️ Not a substitute for sleep.",
    "💡 مشروب شتوي مثالي.": "💡 The perfect winter drink.",
    "💡 2-3 أكواب يومياً بترفع الحرق.": "💡 2-3 cups a day raises calorie burn.",
    "💡 السكر هو اللي بيغير الحسبة.": "💡 The sugar is what changes the maths.",
    "💡 بلبن خالي الدسم أخف.": "💡 Lighter with skim milk.",
    "💡 الحجم الكبير = كوب لبن كامل.": "💡 The large size is a full glass of milk.",
    "⚠️ الكوب الكبير 350+ سعرة.": "⚠️ A large cup is over 350 calories.",
    "⚠️ الكوب = 250+ سعرة بالمكسرات.": "⚠️ A cup with nuts is over 250 calories.",
    "💡 مشبع ودافي — اختيار شتوي ذكي.": "💡 Filling and warming — a smart winter choice.",
    "💡 من غير سكر صفر تقريباً.": "💡 Unsweetened it is nearly zero.",
    "💡 كاكاو خام بلبن خالي أخف بكتير.": "💡 Raw cocoa with skim milk is far lighter.",
    "⚠️ الكوب التقليدي 300+ سعرة.": "⚠️ The traditional cup is over 300 calories.",
    "💡 بالزبادي بدل الآيس كريم.": "💡 With yogurt instead of ice cream.",
    "⚠️ الكوب الكبير = 550+ سعرة.": "⚠️ A large cup is over 550 calories.",
    "💡 من أفضل العصائر الطبيعية.": "💡 One of the best natural juices.",
    "💡 كوب صغير بدون سكر.": "💡 A small glass, unsweetened.",
    "💡 اطلبه ساده.": "💡 Order it plain.",
    "💡 وجبة خفيفة مش مشروب مع الأكل.": "💡 Treat it as a snack, not a drink with a meal.",
    "⚠️ الكوب الكبير = 400+ سعرة.": "⚠️ A large cup is over 400 calories.",
    "💡 بشريحة ليمون بديل ممتاز للكولا.": "💡 With a slice of lemon, an excellent swap for cola.",
    "💡 بعد التمرين الطويل.": "💡 After a long workout.",
    "⚠️ الكوب = 120-150 سعرة.": "⚠️ A cup is 120-150 calories.",
    "💡 مع تمرة واحدة تقليد مثالي.": "💡 With a single date, the perfect tradition.",
    "💡 اختار الدايت منه.": "💡 Choose the diet version.",
    "💡 من غير سكر = مشروب مثالي.": "💡 Unsweetened, it is the ideal drink.",
    "⚠️ العلبة = 3 ملاعق سكر.": "⚠️ One carton = 3 spoons of sugar.",
    "💡 اقرأ إن السكر فعلاً صفر.": "💡 Check the sugar really is zero.",
    "💡 مربعين = 110 سعرة — مقبول.": "💡 Two squares = 110 calories — reasonable.",
    "⚠️ اللوح الصغير = 250+ سعرة.": "⚠️ A small bar is over 250 calories.",
    "⚠️ قطعة صغيرة = 350+ سعرة.": "⚠️ A small piece is over 350 calories.",
    "⚠️ مربع واحد صغير كفاية.": "⚠️ One small square is enough.",
    "⚠️ قطعتين = وجبة كاملة سعرات.": "⚠️ Two pieces is a whole meal in calories.",
    "⚠️ طبق صغير = 400 سعرة.": "⚠️ A small dish = 400 calories.",
    "💡 اختيار معقول بحصة صغيرة.": "💡 A reasonable choice in a small portion.",
    "💡 من غير مكسرات وشربات أخف.": "💡 Lighter without the nuts and syrup.",
    "💡 الدايت جيلي شبه صفر.": "💡 Sugar-free jelly is nearly zero.",
    "💡 كرة واحدة واتبسط.": "💡 One scoop, and enjoy it.",
    "⚠️ العلبة بتخلص من غير ما تحس.": "⚠️ The packet empties before you notice.",
    "⚠️ بالكريمة يتضاعف.": "⚠️ With cream it doubles.",
    "⚠️ واحد = 270+ سعرة.": "⚠️ One is over 270 calories.",
    "⚠️ واحد = ساعة كارديو.": "⚠️ One equals an hour of cardio.",
    "💡 ملعقة صغيرة = 21 سعرة.": "💡 A teaspoon = 21 calories.",
    "💡 ملعقة صغيرة كفاية.": "💡 A teaspoon is enough.",
    "⚠️ كل معلقة صغيرة = 16 سعرة.": "⚠️ Every teaspoon = 16 calories.",
    "⚠️ قطعة صغيرة كفاية.": "⚠️ A small piece is enough.",
    "⚠️ 5 حبات = 300 سعرة.": "⚠️ 5 pieces = 300 calories.",
    "💡 قطايف عصافيري بالقشطة من غير قلي أخف.": "💡 Unfried mini qatayef with cream is lighter.",
    "⚠️ الكحكة = 180-220 سعرة.": "⚠️ One kahk = 180-220 calories.",
    "⚠️ قطعتين وبس.": "⚠️ Two pieces, no more.",
    "⚠️ القطعة الصغيرة = 60 سعرة.": "⚠️ One small piece = 60 calories.",
    "💡 حشوة التمر أفضل من السكر.": "💡 A date filling beats a sugar one.",
    "⚠️ القطعة = 450+ سعرة.": "⚠️ One piece is over 450 calories.",
    "⚠️ حلو لبناني تقيل.": "⚠️ A heavy Lebanese dessert.",
    "⚠️ 3 قطع = 300 سعرة.": "⚠️ 3 pieces = 300 calories.",
    "💡 من غير مكسرات يخف.": "💡 Lighter without the nuts.",
    "💡 بالفواكه تحلية معقولة.": "💡 With fruit it is a reasonable dessert.",
    "⚠️ القطعة = 350+ سعرة.": "⚠️ One slice is over 350 calories.",
    "⚠️ الشريحة = 400+ سعرة.": "⚠️ One slice is over 400 calories.",
    "⚠️ مربع صغير كفاية.": "⚠️ A small square is enough.",
    "⚠️ بالآيس كريم يتخطى 600.": "⚠️ With ice cream it passes 600.",
    "⚠️ الكريب الكامل = 500+ سعرة.": "⚠️ A whole crêpe is over 500 calories.",
    "💡 الحصة الفعلية صغيرة ≈ 30 جم.": "💡 The actual portion is small, about 30 g.",
    "⚠️ قطعتين = 100 سعرة.": "⚠️ Two pieces = 100 calories.",
    "💡 فيها فايدة بس مركزة.": "💡 There is goodness in it, but it is concentrated.",
    "💡 قطعة صغيرة.": "💡 A small piece.",
    "⚠️ الكيس الصغير = 150 سعرة.": "⚠️ A small bag = 150 calories.",
    "⚠️ اللوح = 300 سعرة.": "⚠️ A bar = 300 calories.",
    "⚠️ الملعقة الكبيرة = 100 سعرة.": "⚠️ One tablespoon = 100 calories.",
    "💡 معلقة صغيرة.": "💡 A teaspoon.",
    "⚠️ الأصابع الثلاثة = 350 سعرة.": "⚠️ Three fingers = 350 calories.",
    "💡 2-3 مع الشاي وقفل الباكو.": "💡 2-3 with your tea, then close the packet.",
    "⚠️ واحد = 300+ سعرة.": "⚠️ One is over 300 calories.",
    "⚠️ البسكوتة = 70 سعرة.": "⚠️ One biscuit = 70 calories.",
    "⚠️ الصباع = 80-100 سعرة.": "⚠️ One finger = 80-100 calories.",
    "💡 الواحدة ≈ 6 جم = 23 سعرة.": "💡 One is about 6 g — 23 calories.",
    "💡 معلقة صغيرة — سعراته زي العادي.": "💡 A teaspoon — the calories match ordinary honey.",
    "💡 حبتين = 90 سعرة.": "💡 Two pieces = 90 calories.",
    "💡 اطلبها من غير بطاطس جوه.": "💡 Order it without chips inside.",
    "💡 صوص على الجنب.": "💡 Sauce on the side.",
    "⚠️ من غير بطاطس ومشروب توفر نصها.": "⚠️ Skipping the chips and drink saves half of it.",
    "💡 قطعتين + سلطة = وجبة معقولة.": "💡 Two slices plus salad is a sensible meal.",
    "⚠️ قف عند قطعتين.": "⚠️ Stop at two slices.",
    "⚠️ قطعة صغيرة = 300+ سعرة.": "⚠️ A small piece is over 300 calories.",
    "💡 الطبق الصغير ≈ 550 سعرة — وجبة كاملة.": "💡 The small plate is about 550 calories — a full meal.",
    "💡 فول أكتر وطعمية أقل.": "💡 More ful, less falafel.",
    "💡 من غير بطاطس جنبه.": "💡 Without chips alongside.",
    "💡 نصفه كفاية مع سلطة.": "💡 Half of it with salad is enough.",
    "💡 مشوي بدل بانيه يوفر 40%.": "💡 Grilled instead of breaded saves 40%.",
    "⚠️ في الفرن أخف.": "⚠️ Lighter in the oven.",
    "💡 الرولات المقلية والصوصات هي الفخ.": "💡 The fried rolls and the sauces are the trap.",
    "⚠️ الكيس العائلي فخ حقيقي.": "⚠️ The family bag is a genuine trap.",
    "⚠️ القطعة المتوسطة = 450 سعرة.": "⚠️ A medium portion = 450 calories.",
    "💡 5-6 قطع مع زبادي وجبة.": "💡 5-6 pieces with yogurt makes a meal.",
    "💡 8 أصابع حصة.": "💡 8 rolls is a portion.",
    "💡 الطبق المتوسط ≈ 400 جم = 660 سعرة.": "💡 A medium plate is about 400 g — 660 calories.",
    "💡 اللحم بدون الجلد والدهن الظاهر.": "💡 Take the meat without the skin or visible fat.",
    "💡 زود السلطة جنبه.": "💡 Add plenty of salad alongside.",
    "⚠️ الجميد يرفع الدهون والملح.": "⚠️ The jameed pushes up both fat and salt.",
    "💡 اشوي الباذنجان بدل قليه.": "💡 Grill the eggplant instead of frying it.",
    "💡 التقلية هي مصدر الدهون.": "💡 The fried garlic topping is where the fat comes from.",
    "💡 حمص العيش في الفرن مش القلي.": "💡 Toast the bread in the oven rather than frying it.",
    "⚠️ طبق العيد = 700+ سعرة.": "⚠️ The Eid plate is over 700 calories.",
    "💡 فطار بروتيني ممتاز.": "💡 An excellent high-protein breakfast.",
    "💡 مشوي مش مقلي!": "💡 Grilled, not fried!",
    "💡 مع رز محسوب وجبة كاملة.": "💡 With a measured portion of rice it is a full meal.",
    "💡 اختيار دايت ممتاز.": "💡 An excellent diet choice.",
    "💡 بالشوربة مش بالتسبيك.": "💡 Cooked in broth, not in a fried base.",
    "💡 10 أصابع = 340 سعرة.": "💡 10 rolls = 340 calories.",
    "💡 اطلبها قليلة الدهن.": "💡 Ask for the lean version.",
    "💡 بروتين عالي — قلل العيش معاه.": "💡 High protein — go easy on the bread with it.",
    "💡 صحي أصلاً — بالتوفيق مع الكسكسي.": "💡 Healthy as it is — mind the couscous alongside.",
    "💡 مشبعة وقيمتها عالية.": "💡 Filling, and genuinely nutritious.",
    "💡 بالليمون والكمون — من غير عيش محمر.": "💡 With lemon and cumin, and no fried bread.",
    "💡 قشط الدهن من الوش.": "💡 Skim the fat off the top.",
    "💡 بتقلل كمية الأكل بعدها.": "💡 It cuts how much you eat afterwards.",
    "💡 صعيدي أصيل ومفيد.": "💡 Authentically Upper Egyptian, and good for you.",
    "⚠️ القطعة = 400+ سعرة.": "⚠️ One portion is over 400 calories.",
    "⚠️ ضعف سعرات الرز العادي.": "⚠️ Twice the calories of plain rice.",
    "💡 وجبة ساحلية متوازنة.": "💡 A balanced coastal meal.",
    "⚠️ قطعة صغيرة واكتفي.": "⚠️ One small piece, and leave it there.",
    "💡 البسمتي أخف من الرز العادي.": "💡 Basmati is lighter than ordinary rice.",
    "💡 قطعتين مع سلطة كفاية.": "💡 Two pieces with salad is enough.",
    "💡 نصها بالجبنة القريش أخف.": "💡 Half of it with cottage cheese is lighter.",
    "💡 في الفرن توفر نص السعرات.": "💡 Baking saves half the calories.",
    "💡 القلاية الهوائية هي الحل.": "💡 The air fryer is the answer.",
    "💡 كبة بالصينية أخف.": "💡 Tray-baked kibbeh is lighter.",
    "💡 من أصح السلطات العربية.": "💡 One of the healthiest Arab salads.",
    "💡 عيش مشوي مش مقلي.": "💡 Toasted bread, not fried.",
    "💡 مع المشويات أساسية.": "💡 Essential alongside grilled meat.",
    "💡 ملعقتين حصة.": "💡 Two tablespoons is a portion.",
    "💡 شيل الجلد توفر 60 سعرة.": "💡 Removing the skin saves 60 calories.",
    "⚠️ القطعتين = 500+ سعرة.": "⚠️ Two pieces is over 500 calories.",
    "💡 شيل القشرة لو مضطر.": "💡 Peel off the coating if you have to have it.",
    "⚠️ مرات نادرة.": "⚠️ Rarely.",
    "💡 بالخضار والصلصة الحارة أخف.": "💡 Lighter with vegetables and hot salsa.",
    "💡 اطلب صحن + سلطة.": "💡 Order it as a plate with salad.",
    "💡 بالزبادي بدل الصوص الأبيض.": "💡 With yogurt instead of the white sauce.",
    "💡 2-3 قطع مع شوربة وجبة.": "💡 2-3 pieces with soup makes a meal.",
    "💡 نصه كفاية.": "💡 Half is enough.",
    "💡 من غير بطاطس جوه.": "💡 Without chips inside.",
    "💡 بالصلصة مش بالكريمة.": "💡 In tomato sauce, not cream.",
    "💡 بزيت الزيتون مش المايونيز.": "💡 With olive oil, not mayonnaise.",
    "⚠️ الصوص على الجنب دايماً.": "⚠️ Always ask for the dressing on the side.",
    "💡 بالليمون بدل المايونيز.": "💡 With lemon instead of mayonnaise.",
    "⚠️ سناك مش وجبة.": "⚠️ A snack, not a meal.",
    "⚠️ الساندوتش = 750+ سعرة.": "⚠️ The sandwich is over 750 calories.",
    "💡 في الفرن بالبابريكا بديل رائع.": "💡 Oven-baked with paprika is a great alternative.",
    "⚠️ 6 حلقات = 280 سعرة.": "⚠️ 6 rings = 280 calories.",
    "⚠️ القطعتين = 250 سعرة.": "⚠️ Two pieces = 250 calories.",
    "⚠️ الطبق المشترك خدعة — بتاكله لوحدك.": "⚠️ The sharing platter is a con — you finish it alone.",
    "💡 بروتين مزدوج يشبع لساعات.": "💡 Double protein that keeps you full for hours.",
    "⚠️ البسطرمة مملحة — للضغط لأ.": "⚠️ Basturma is salty — not for high blood pressure.",
    "💡 بالطماطم والخيار يخف ويحلى.": "💡 Tomato and cucumber lighten it and improve it.",
    "💡 نص ساندوتش قبل التمرين.": "💡 Half a sandwich before training.",
    "⚠️ الكيس الصغير = 160 سعرة.": "⚠️ A small bag = 160 calories.",
    "💡 اختيار أذكى لو مصمم.": "💡 The smarter pick if you insist.",
    "💡 نسخة بالحليب أخف.": "💡 The milk-based version is lighter.",
    "💡 من غير كريمة ع الوش.": "💡 Without the swirl of cream on top.",
    "💡 بداية فاخرة قليلة السعرات.": "💡 A luxurious, low-calorie starter.",
}
